export const ASSIGN = 'ASSIGN'
export const ACTION = 'ACTION'
export const ENTER_ROOM = 'ENTER_ROOM'
export const CREATE_ROOM = 'CREATE_ROOM'
export const PLAYER_1 = 'PLAYER_1'
export const PLAYER_2 = 'PLAYER_2'
export const SURRENDER = 'SURRENDER'
