name: Build and Deploy to Production

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'functions/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    env:
       CI: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Node.js project for production
      run: yarn install --production

    - name: Generate static files
      run: yarn generate --fail-on-page-error
      env:
        API_KEY: ${{ secrets.API_KEY_PROD }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN_PROD }}
        DATABASE_URL: ${{ secrets.DATABASE_URL_PROD }}
        PROJECT_ID: ${{ secrets.PROJECT_ID_PROD }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET_PROD }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID_PROD }}
        APP_ID: ${{ secrets.APP_ID_PROD }}
        MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID_PROD }}

    - name: Archive Production Artifact
      uses: actions/upload-artifact@master
      with:
        name: dist
        path: dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



